# Generated by Django 3.2 on 2022-01-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220125_1638'),
        ('products', '0002_auto_20220125_2351'),
    ]

    operations = [
    ]
